# Generated by Django 5.2 on 2025-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_extra',
            name='hobbie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
